# This is the "trainslation" table for subject names...

# ...because, some of the subject names in the dataset unnecessarily long, rarely used 
# or simply weird. "Business  Studies:Single"?!

subject_map = {
    "Accounting/Finance": "Accounting",
    "Additional Mathematics": "Additional Maths",
    # "Ancient History": "",
    # "Anthropology": "",
    # "Applied Art & Design": "",
    # "Applied Business": "",
    # "Applied Engineering": "",
    # "Applied ICT": "",
    # "Applied Science": "",
    # "Arabic": "",
    # "Archaeology": "",
    # "Art & Design": "",
    "Art & Design (3d Studies)": "3D Studies",
    "Art & Design (Critical Studies)": "Critical Studies",
    "Art & Design (Fine Art)": "Fine Art",
    "Art & Design (Graphics)": "Graphic Communication",
    "Art & Design (Photography)": "Photography",
    "Art & Design (Textiles)": "Textile Design",
    # "Bengali": "",
    # "Biology": "",
    "Business  Studies:Single": "Business Studies",
    # "Business Studies & Economics": "",
    # "Chemistry": "",
    # "Chinese": "",
    # "Classical Civilisation": "",
    # "Classical Greek": "",
    "Classics (General)": "Classics",
    # "Communication Studies": "",
    "Computer Studies/Computing": "Computing",
    # "Critical Thinking": "",
    # "D&T Food Technology": "",
    # "D&T Product Design": "",
    # "D&T Systems & Control": "",
    # "D&T Textiles Technology": "",
    # "Dance": "",
    # "Drama & Theatre Studies": "",
    # "Dutch": "",
    # "Economics": "",
    # "Electronics": "",
    # "English Language": "",
    # "English Language & Literature": "",
    # "English Literature": "",
    # "Environmental Science": "",
    # "Expressive Arts & Performance Studies": "",
    # "Film Studies": "",
    # "French": "",
    # "General Studies": "",
    # "Geography": "",
    # "Geology": "",
    # "German": "",
    # "Government & Politics": "",
    # "Gujarati": "",
    # "Health & Social Care": "",
    # "History": "",
    # "History of Art": "",
    # "Home Economics: Food": "",
    "Information & Communications Technology": "ICT",
    # "Italian": "",
    # "Japanese": "",
    # "Latin": "",
    # "Law": "",
    # "Leisure & Recreation": "",
    "Logic/ Philosophy": "Philosophy",
    "Mathematics": "Maths",
    "Mathematics (Further)": "Further Maths",
    "Mathematics (Pure)": "Pure Maths",
    "Mathematics (Statistics)": "Statistics",
    "Media/Film/Tv Studies": "Media Studies",
    # "Media: Communication & Production": "",
    # "Modern Greek": "",
    # "Modern Hebrew": "",
    # "Music": "",
    # "Music Technology": "",
    # "Other Classical Languages": "",
    # "Performing Arts": "",
    # "Persian": "",
    "Physical Education/Sports Studies": "Physical Education",
    # "Physics": "",
    # "Polish": "",
    # "Portuguese": "",
    # "Psychology": "",
    # "Punjabi": "",
    # "Religious Studies": "",
    # "Russian": "",
    # "Science in Society": "",
    "Social Science: Citizenship": "Citizenship",
    # "Sociology": "",
    # "Spanish": "",
    # "Travel & Tourism": "",
    # "Turkish": "",
    # "Urdu": "",
    "Use of Mathematics": "Use of Maths",
    "Welsh (Second Language)": "Welsh",
    # "World Development": ""
}

def subject_name(name):
    try:
        return subject_map[name]
    except KeyError:
        return name